<a href="https://colab.research.google.com/github/juanalvarez2491-web/Entregables-BIT-JuanCarlosAlvarezOchoa/blob/main/Actividad_2_Limpieza_y_an%C3%A1lisis_de_datos_con_Pandas_%2B_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Actividad 2: Limpieza y análisis de datos con Pandas + NumPy

Contexto
Un equipo de investigadores está recopilando información sobre observaciones de animales realizadas en diferentes países de Europa Central y Oriental.
Los datos fueron recolectados por diferentes personas y presentan problemas de calidad: valores faltantes, registros duplicados, formatos inconsistentes, errores en los datos y diferentes formas de representar algunas variables.
Antes de realizar cualquier análisis, es necesario diagnosticar y limpiar la información.
Tu trabajo como analista de datos será preparar esta base para que pueda ser utilizada posteriormente en un análisis de biodiversidad.

# 1. Diagnóstico inicial

Carga el dataset utilizando Pandas y realiza una exploración inicial.
Debes responder mediante código:

    • Cuántas filas y columnas tiene el DataFrame?
    • Cuáles son las columnas y qué tipo de dato tiene cada una?
    • Cuántos valores faltantes existen por columna?
    • Cuántos registros duplicados existen?
    • Utiliza unique() o value_counts() para identificar categorías inconsistentes o valores sospechosos.

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files
uploaded = files.upload()

Saving animal_data.csv to animal_data.csv

In [3]:
df = pd.read_csv("animal_data.csv",sep=";")

df.head()

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.01.2024,James Johnson
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.02.2024,James Johnson
2,European bison,Poland,930.0,335.0,male,NaN,52.828845,23.820144,Szefu,01.03.2024,Anne Anthony
3,European bison,Poland,909.0,311.0,not determined,NaN,52.830509,23.826849,NaN,01.03.2024,Anne Anthony
4,European bison™,Poland,581.0,277.0,female,NaN,52.834109,23.807093,NaN,01.03.2024,Anne Anthony

**Cuántas filas y columnas tiene el DataFrame?**

R\= El DataFrame "animal_data" tien un total de 1011 filas y 11 columna

In [4]:
df.shape

(1011, 11)

**Cuáles son las columnas y qué tipo de dato tiene cada una?**

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1011 entries, 0 to 1010
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Animal type       991 non-null    object
 1   Country           999 non-null    object
 2   Weight kg         984 non-null    float64
 3   Body Length cm    984 non-null    float64
 4   Gender            992 non-null    object
 5   Animal code       0 non-null      float64
 6   Latitude          913 non-null    float64
 7   Longitude         913 non-null    float64
 8   Animal name       52 non-null     object
 9   Observation date  1011 non-null   object
 10  Data compiled by  1011 non-null   object
dtypes: float64(5), object(6)
memory usage: 87.0+ KB

**Cuántos valores faltantes existen por columna?**

In [6]:
df.isnull().sum()

Animal type           20
Country               12
Weight kg             27
Body Length cm        27
Gender                19
Animal code         1011
Latitude              98
Longitude             98
Animal name          959
Observation date       0
Data compiled by       0
dtype: int64

In [7]:
for col in df.columns:
    error = df[col].isin(["ERROR", "UNKNOWN"]).sum()
    if error > 0:
        print(col, error)

**Cuántos registros duplicados existen?**

R\= Existen un total de 167 valores duplicados en este DataFrame

In [8]:
df.duplicated().sum()

np.int64(167)

In [9]:
df[df.duplicated()].head()

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
51,red squirel,Poland,0.308,22.0,female,NaN,52.241273,21.055745,Basia,01.03.2024,Anne Anthony
52,red squirrel,PL,0.348,20.0,female,NaN,52.242060,21.057802,NaN,01.03.2024,Anne Anthony
53,red squirrel,Poland,0.316,20.0,male,NaN,52.240035,21.056188,Lolek,01.03.2024,Anne Anthony
54,red squirrel,Poland,0.340,21.0,NaN,NaN,52.240284,21.051948,NaN,01.03.2024,Anne Anthony
55,red squirrel,Poland,0.333,21.0,male,NaN,NaN,NaN,NaN,01.03.2024,Anne Anthony

**Utiliza unique() o value_counts() para identificar categorías inconsistentes o valores sospechosos**

In [10]:
df["Animal type"].value_counts()

Animal type
red squirrel       543
hedgehog           274
lynx                61
European bison      49
red squirrell       22
red squirel         14
lynx?               10
European bison™      6
European buster      4
European bisson      4
ledgehod             3
wedgehod             1
Name: count, dtype: int64

In [11]:
df["Country"].value_counts()

Country
Poland            291
Germany           176
Slovakia          151
Hungary           146
Czech Republic    103
Austria            74
PL                 15
HU                 11
Hungry             10
CZ                  5
DE                  5
Czech               4
Australia           4
CC                  4
Name: count, dtype: int64

In [12]:
df['Gender'].value_counts()

Gender
male              499
female            488
not determined      5
Name: count, dtype: int64

In [13]:
df["Animal name"].value_counts()

Animal name
Bob Bobson    18
Basia         10
Lola           9
Lolek          4
Zuzia          4
Puchatek       2
Sissi          2
Szefu          1
Klucha         1
Bibi           1
Name: count, dtype: int64

In [14]:
df["Data compiled by"].value_counts()

Data compiled by
Anne Anthony     473
Bob Bobson       259
John Johnson     249
James Johnson     30
Name: count, dtype: int64

In [15]:
df["Observation date"].value_counts()

Observation date
01.03.2024    61
02.03.2024    47
06.04.2024    45
04.03.2024    43
02.04.2024    41
              ..
07.06.2024     1
03.14.2024     1
03.13.2024     1
03.11.2024     1
8 May 2024     1
Name: count, Length: 114, dtype: int64

In [16]:
df["Body Length cm"].value_counts()

Body Length cm
20.0     129
19.0     124
22.0     118
21.0     114
23.0     101
        ...
115.0      1
84.0       1
87.0       1
210.0      1
107.0      1
Name: count, Length: 112, dtype: int64

In [63]:
df[df["Body Length cm"] < 0][["Animal type", "Body Length cm"]].head()

      Animal type  Body Length cm
47       Hedgehog           -16.0
124  Red Squirrel           -19.0
162  Red Squirrel           -19.0
225      Hedgehog           -19.0

In [17]:
df['Longitude'].value_counts()

Longitude
34.896734    4
21.033750    2
23.817037    2
23.813638    2
21.033642    2
            ..
11.190836    1
11.185570    1
11.185855    1
11.188761    1
23.815823    1
Name: count, Length: 743, dtype: int64

In [18]:
df['Latitude'].value_counts()

Latitude
 52.211797    4
 52.212001    4
 50.041366    4
-2.023546     4
 52.241638    4
             ..
 49.053342    1
 49.056471    1
 50.636564    1
 49.055537    1
 50.636869    1
Name: count, Length: 735, dtype: int64

In [19]:
df["Weight kg"].value_counts()

Weight kg
0.700      48
0.600      46
0.800      42
1.100      36
0.900      28
           ..
11.000      1
0.309       1
0.331       1
13.000      1
727.000     1
Name: count, Length: 195, dtype: int64

In [62]:
df[df["Weight kg"] < 0][["Animal type", "Weight kg"]].head()

      Animal type  Weight kg
457  Red Squirrel     -0.251
503  Red Squirrel     -0.250
663  Red Squirrel     -0.252

In [20]:
df['Animal code'].value_counts()

Series([], Name: count, dtype: int64)

**Escribe una breve explicación de al menos 3 problemas de calidad que hayas encontrado.**

R\= Al verificar el dataset me encuentro con varios problemas de calidad como lo son:

1. El faltante de una cantidad grande de datos en la gran mayoria de columnas
2. Inconsitencias en la ortografia o escritura, como algunos paises escritos con abreviaturas
3. Una gran cantidad de datos duplicados
4. la base de datos estaba agrupando las diferentes columnas en una sola
5. Valores negativos en las columnas de peso en kilos y longitud del cuerpo en cm

# 2.Limpieza de datos

Realiza las transformaciones necesarias para obtener un DataFrame consistente.
Debes:

    • Identificar las columnas con valores faltantes y aplica una estrategia de tratamiento adecuada.
    • Detectar y elimina los registros duplicados cuando corresponda.
    • Convertir las columnas que tengan tipos de datos incorrectos.
    • Identificar al menos dos variables categóricas que presenten inconsistencias y estandarízalas.
    • Después de realizar la limpieza, demuestra mediante código que las transformaciones fueron aplicadas correctamente.

**• Detectar y elimina los registros duplicados cuando corresponda.**

In [21]:
df = df.drop_duplicates()

df.shape

(844, 11)

** Identificar las columnas con valores faltantes y aplica una estrategia de tratamiento adecuada.**

In [22]:
df["Animal type"] = (
    df["Animal type"]
    .str.strip()
    .str.lower()
    .str.title()
)

In [23]:
df["Animal type"] = (
    df["Animal type"]
    .str.replace("™", "", regex=False)
    .str.replace("?", "", regex=False)
)

In [24]:
df["Animal type"] = (
    df["Animal type"]
    .str.replace("European Bisson", "European Bison", regex=False)
)

In [25]:
df["Animal type"] = (
    df["Animal type"]
    .str.replace("Red Squirel", "Red Squirrell", regex=False)
)

In [26]:
df["Animal type"] = (
    df["Animal type"]
    .str.replace("Red Squierrel", "Red Squirrel", regex=False)
)

In [27]:
df["Animal type"] = (
    df["Animal type"]
    .str.replace("Red Squirrell", "Red Squirrel", regex=False)
)

In [28]:
df["Animal type"].value_counts()

Animal type
Red Squirrel       413
Hedgehog           274
Lynx                71
European Bison      59
European Buster      4
Ledgehod             3
Wedgehod             1
Name: count, dtype: int64

In [29]:
df["Country"] = (
    df["Country"]
    .str.strip()
    .str.lower()
    .str.title()
)

In [30]:
df["Country"] = (
    df["Country"]
    .str.replace("Pl", "Poland", regex=False)
)

In [31]:
df["Country"] = (
    df["Country"]
    .str.replace("De", "Germany", regex=False)
)

In [32]:
df["Country"] = (
    df["Country"]
    .str.replace("Cc", "Cz", regex=False)
)

In [33]:
df["Country"] = (
    df["Country"]
    .str.replace("Czech Republic", "Czech", regex=False)
)

In [34]:
df["Country"] = (
    df["Country"]
    .str.replace("Czech Republic", "Czech", regex=False)
)

In [35]:
df["Country"] = (
    df["Country"]
    .str.replace("Cz", "Czéch", regex=False)
)

In [36]:
df["Country"] = (
    df["Country"]
    .str.replace("Czéchech", "Czéch", regex=False)
)

In [37]:
df["Country"] = (
    df["Country"]
    .str.replace("Czéch", "Czech", regex=False)
)

In [38]:
df["Country"] = (
    df["Country"]
    .str.replace("Hungry", "Hungary", regex=False)
)

In [39]:
df["Country"] =(
    df["Country"]
    .str.replace("Hu", "Hungary", regex=False)
)

In [40]:
df["Country"] = (
    df["Country"]
    .str.replace("Hungaryngaryngaryngary", "Hungary", regex=False)
)

In [41]:
df["Country"] = (
    df["Country"]
    .str.replace("Hungaryngaryngary", "Hungary", regex=False)
)

In [42]:
df["Gender"] = df["Gender"].fillna("not determined")

In [43]:
df["Animal name"] = df["Animal name"].fillna("not determined")

In [44]:
df["Latitude"] = df["Latitude"].fillna("not determined")

In [45]:
df["Longitude"] = df["Longitude"].fillna("not determined")

In [46]:
df["Animal type"] = df["Animal type"].fillna("not determined")

In [47]:
df["Country"] = df["Country"].fillna("not determined")

In [48]:
df["Weight kg"] = df["Weight kg"].fillna("not determined")

In [49]:
df["Body Length cm"] = df["Body Length cm"].fillna("not determined")

In [50]:
df["Animal code"] = df["Animal code"].fillna("not determined")

In [51]:
df["Weight kg"] = pd.to_numeric(
    df["Weight kg"],
    errors="coerce"
)

df["Weight kg"].dtype

dtype('float64')

In [52]:
df["Body Length cm"] = pd.to_numeric(
    df["Body Length cm"],
    errors="coerce"
)

df["Body Length cm"].dtype

dtype('float64')

In [53]:
df["Latitude"] = pd.to_numeric(
    df["Latitude"],
    errors="coerce"
)

df["Latitude"].dtype

dtype('float64')

In [54]:
df["Longitude"] = pd.to_numeric(
    df["Longitude"],
    errors="coerce"
)

df["Longitude"].dtype

dtype('float64')

In [55]:
df["Observation date"] = pd.to_datetime(
    df["Observation date"],
    errors="coerce",
    format="mixed",
    dayfirst=True
)

In [56]:
df.head()

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
0,not determined,not determined,NaN,NaN,not determined,not determined,NaN,NaN,not determined,2024-01-03,James Johnson
1,not determined,not determined,NaN,NaN,not determined,not determined,NaN,NaN,not determined,2024-02-03,James Johnson
2,European Bison,Poland,930.0,335.0,male,not determined,52.828845,23.820144,Szefu,2024-03-01,Anne Anthony
3,European Bison,Poland,909.0,311.0,not determined,not determined,52.830509,23.826849,not determined,2024-03-01,Anne Anthony
4,European Bison,Poland,581.0,277.0,female,not determined,52.834109,23.807093,not determined,2024-03-01,Anne Anthony

In [57]:
df[df["Body Length cm"] < 0][["Animal type", "Body Length cm"]].head(20)

      Animal type  Body Length cm
47       Hedgehog           -16.0
124  Red Squirrel           -19.0
162  Red Squirrel           -19.0
225      Hedgehog           -19.0

In [64]:
df[df["Weight kg"] < 0][["Animal type", "Weight kg"]].head()

      Animal type  Weight kg
457  Red Squirrel     -0.251
503  Red Squirrel     -0.250
663  Red Squirrel     -0.252